
title = "Forest"

[paths]
background_image_path = "raw_images/biomes/forest_background.png"
title_banner_path = "raw_images/banners/title_banner_2.png"
biome_icon_path = "raw_images/icons/forest_icon.png"
